server:
  port: 8080

spring:
  profiles:
    active: dev

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

graphql:
  spqr:
    gui:
      enabled: true

walki:
  apple:
    base-url: https://appleid.apple.com
    service-id: com.bside.walki # client_id, aud
    team-id: P72UR4K32D
    key-id: Y97F78DFRD
    key-path: apple/AuthKey_Y97F78DFRD.p8
