server:
  port: 8080

spring:
  profiles:
    active: dev

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

graphql:
  spqr:
    gui:
      enabled: true

walki:
  apple:
    base-url: https://appleid.apple.com
    service-id: bside.palmtree # client_id, aud
    team-id: P72UR4K32D
    key-id: 785WUJMK9U
    key-path: auth/AuthKey_785WUJMK9U.p8
